### ISSUE TITLE
недостаточно документации для docCookies

### ISSUE THREAD

**Issue by aalexeev239** [o0/js-intensive#10]
Новичку не очевидно, как работает библиотека. Следует дать пояснения и примеры использования, как в MDN. Особенно непонятно, как заполнять значение expires.

@dmitrylebedev нашел версию с документацией https://github.com/bibliolabs/docCookies

**Comment by dmitrylebedev** [comment]
@aalexeev239 Игорю уже было отправлено в слак, но напомнить не помешает
