### ISSUE TITLE
Ошибка с предзаполнением полей x/y в Кексограмме.

### ISSUE THREAD

**Issue by Shushik** [o0/js-intensive#11]
Была обнаружена в рамках проверки домашки по module6-task2.

Состоит в том, что если взять большую фотку и «сохранить», а затем взять фотку, которая по ширине или высоте меньше предыдущей, то поля будут предзаполнены значениями от предыдущей фотки, которые, соответственно больше.

Возможно, стоит сделать дополнительную проверку?

**Comment by o0** [comment]
С новым механизмом должно быть исправлено, потому что событие, которое ребята используют для синхронизации срабатывает и по загрузке новой фотки
