### ISSUE TITLE
Ссылка на выполнение курса в заданиях

### ISSUE THREAD

**Issue by kaineer** [o0/js-intensive#12]
Например здесь: https://up.htmlacademy.ru/javascript/3/tasks/1

Единственная подсказка, где находится ссылка - изменение курсора при наведении.

Если бы название курса было подсвечено "синеньким" цветом, или бы была кнопка "Выполнить", это, на мой взгляд, вызывало бы меньше проблем с переходом по ссылке.

**Comment by o0** [comment]
Стало лучше с редизайном. Ну и мне надо чаще заглядывать в этот репозиторий)
