### ISSUE TITLE
Курс "Введение в Javascript", задача 10

### ISSUE THREAD

**Issue by kaineer** [o0/js-intensive#13]
Перед изучающим переменные ставятся цели:

  * Перепишите код таким образом, чтобы сторона квадрата задавалась переменной `side`
  * Перепишите код так, чтобы смещение квадрата по оси x задавалось переменной `displacementX`

Решение, которое, внезапно, проходит:

```.js
var side = 300;
var displacementX = 0;
ctx.moveTo(displacementX, displacementX);
ctx.lineTo(side, displacementX);
ctx.lineTo(side, side);
ctx.lineTo(displacementX, side);
ctx.lineTo(displacementX, displacementX);
ctx.stroke();
```

Решение, которое в данном случае имеет смысл:

```.js
var side = 300;
var displacementX = 0;

ctx.moveTo(displacementX, 0);
ctx.lineTo(displacementX + side, 0);
ctx.lineTo(displacementX + side, side);
ctx.lineTo(displacementX, side);
ctx.lineTo(displacementX, 0);
ctx.stroke();
```

То, как производится проверка сейчас, сеет сомнения и ересь. Прошу исправить. :disappointed:

**Comment by o0** [comment]
Дубликат вот этого: https://github.com/htmlacademy/yomoyo/issues/38. Лучше все держать в одном месте (а их и так два:)
