### ISSUE TITLE
Вводный раздел, задание #5, "код и магия"

### ISSUE THREAD

**Issue by kaineer** [o0/js-intensive#14]
Мелочи, а неверно:

  1. Причём управление происходит с помощью стрелок и пробела, как на компьютере. (На самом деле, ещё задействован **левый shift**).
  2. стреляет фаерболом (предлагаю формулировку "стреляет фаерболом и не попадает в крону дерева", потому что в момент выстрела никакого сообщения не появляется :)

**Comment by o0** [comment]
Поправил в последнем (5) интенсиве, из него будет все переноситься в новый поток и ошибка исправится
