### ISSUE TITLE
Опечатка в формулировке Б5

### ISSUE THREAD

**Issue by kaineer** [o0/js-intensive#15]
В формулировке критерия Б5 написано:

> Б5. Код оформлен единообразно и соответствует гайдлану.

Прошу поправить на

> Б5. Код оформлен единообразно и соответствует гайдлайну.

(или объяснить мне, кто такой гайдлан :)

**Comment by o0** [comment]
Отправил на ревью, закрою баг, чтобы не забыть про него опять тут:)
