### ISSUE TITLE
Презентация первой лекции

### ISSUE THREAD

**Issue by o0** [o0/js-intensive#2]
- [x] запятые на слайде 88
- [x] добавить фотошоп в примеры где работает JS
- [x] формулировка с консольным JS: рассказать, что он работает в консоли, но так, чтобы народ не путал с XBox.
- [x] подробней рассказать про нотацию записи функций, показать примеры.

**Comment by o0** [comment]
Предложение по консоли: использовать "терминал".

**Comment by princed** [comment]
Спецификация `getMessage(a:*, b:*=):string` в задании напрочь запутала студента. 

Кажется, нужно ещё пару-тройку слайдов с настоящими примерами спецификаций (вместо спецификации спецификации вида `functionName(arg:type):type`) и реальных функций, которые им соответствуют.

Либо, как вариант, вообще выкинуть напрочь всю эту муть про спецификации и писать в задании русским языком..

**Comment by o0** [comment]
@princed хорошее замечание. Я склоняюсь к варианту показывать больше примеров, потому что я буду такой нотацией пользоваться дальше в лекциях, чтобы рассказать как что работает. Спасибо!

**Comment by princed** [comment]
Тогда пройдись по этому ещё раз хорошенько на следующей лекции.

**Comment by princed** [comment]
Слайды из картинок — очень неудобно, невозможно искать по ним!

**Comment by o0** [comment]
Слайды из кода в редакторе, особенно с консолью не картинками — практически невозможно:) Мы готовим к следующим потокам демку — онлайн-редактор с переключениями состояния, которая бы дублировала то, о чем говорится в презентации. Ну и больше курсов.

Но я попробую:)

**Comment by princed** [comment]
Можно же просто код вставлять с подсветкой, нет?
