### ISSUE TITLE
Ошибка в библиотеке работы с куками

### ISSUE THREAD

**Issue by zeckson** [o0/js-intensive#7]
Строчка:
```
sExpires = vEnd === Infinity ? "; expires=Fri, 31 Dec 9999 23:59:59 GMT" : "; max-age=" + vEnd
```
Неверная т.к. max-age параметр принимает секунды, а арифметика над датами выполняется в миллисекундах. Нужно либо делить здесь на 1000, либо как-то обязывать передвать секунды, вместо миллисекунд.

**Comment by o0** [comment]
o0. Вот это подстава. Кк, давай поделим, но скачанную версию уже не починишь.

**Comment by o0** [comment]
Готово. Новая версия по тому же урлу.

**Comment by zeckson** [comment]
Я бы на самом деле там бы не выпендривался и написал бы `"; expires=" + new Date(vEnd).toUTCString(); - хотя это тоже не совсем верно т.к. старый формат кук v1 подразумевает только GMT таймзону =(
