### ISSUE TITLE
Ошибки в задании "Валидация (module3-task1)"

### ISSUE THREAD

**Issue by zeckson** [o0/js-intensive#8]
- [x] 1! Неточность описания задания. Сказано:
```
Ваша задача — написать сценарий валидации формы кадрирования изображения. Ограничения на ввод данных:

Сумма значений полей «слева» и «сторона» не должна быть больше ширины исходного изображения
Сумма значений полей «сверху» и «сторона» не должна быть больше высоты исходного изображения

Другими словами, «кадр» должен находится в пределах исходного изображения.
```
Неверное логическое заключение:
Указаные ограничения на ввод данных не перечисляют всех ситаций когда "кадр" может находится вне предеов исходного изображения, например - заданы отрицательные координаты или отрицательный размер кадра.
Неясно условие когда задание считается верным - когда выполнены вышеуказанные ограничения или когда «кадр» находится в пределах исходного изображения.

- [x] 2! "кадр" должен (что делать?) находитЬся

- [x] 3! В задании указано:
```
Если данные, введенные в форму невалидны, форму должно быть невозможно отправить. При этом кнопка отправки должна быть деактивирована (добавлен атрибут disabled).
```
Если выполнить условие "добавлен атрибут disabled", то исправить введенные значения увы уже невозможно т.к. хэндлер по проверке больше вызван не будет, т.к. кнопка на которой висит клик - disabled.
Выполнить это условие не представляется возможным, либо я не понимаю что имеется ввиду.

- [x] 4! На "disabled" кнопке нет специального стиля, что делает ее неотличимой от не disabled кнопки.

**Comment by o0** [comment]
1. Верно! Учти это, пожалуйста, при проверке. Я поправлю задание (вместе с -ться), но или сегодня вечером или завтра, потому что сегодня приоритет — лекция.
2. Хэндлер по проверке можно вызывать по-разному. Например при изменении полей по onchange и oninput. Необязательно, чтобы это происходило по нажатию на submit.

**Comment by zeckson** [comment]
Студент просто пытался правильно определить поведение функции:
```
  /**
 * Проверяет, валидны ли данные, в форме кадрирования.
 * @return {boolean}
 */
  function resizeFormIsValid() {
```
Что не противоречит условию задания но disabled выставлять увы внутри этой функции нельзя.
К тому же как я упомянул в 4 пункте кнопка никак не меняет своего вида, что добавляет еще большего непонимания что происходит.

**Comment by o0** [comment]
Да, согласен, с функцией большая проблема. К следующему потоку я переделаю код так, чтобы решение было изолировано или не противоречило коду, многие теряются. Нужны дополнительные проверки, однозначно.

**Comment by o0** [comment]
По поводу 3 рассказал на лекции как проверять валидность полей по изменению значения в форме. Можно было рассказать про событие `invalid`, но это один из подходов и, кажется, лучше проверять валидность сразу после ввода значения в поле. В любом случае к следующему потоку тут есть над чем подумать.
